spring:
  application:
    name: server
server:
  port: 7001
eureka:
  instance:
    hostname: 192.168.1.130

  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://192.168.1.130:7001/eureka/