server:
  port: 9092


spring:
  datasource:
    url: jdbc:mysql://192.168.2.109:3306/Test?serverTimezone=UTC&characterEncoding=utf-8
    username: root
    password: example2020!@#
    driver-class-name: com.mysql.cj.jdbc.Driver
    dbcp2:
      max-idle: 10
      max-total: 50
      max-wait-millis: 10000
      initial-size: 5
      default-transaction-isolation: 2

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  database-platform: org.hibernate.dialect.MySQLDialect
  redis:
    host: 192.168.2.109
    port: 6379
    jedis:
      pool:
        max-idle: 10
        max-wait: 2000
        max-active: 10
    database: 0
    timeout: 1000
    password: example2020!@#
  jackson:
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: true
    date-format: yyyy-MM-dd HH:mm:ss


logging:
  level:
    root: info
    org:
      sprintframework: warn

springdoc:
  api-docs:
    path: /api-doc
